# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0004_message_reply_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='mailer', verbose_name='file')),
            ],
            options={
                'verbose_name': 'attachment',
                'verbose_name_plural': 'attachments',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='template_slug',
            field=models.SlugField(blank=True, null=True, verbose_name='template slug'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='message',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], default=2, verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipients',
            field=models.TextField(blank=True, null=True, verbose_name='recipients'),
        ),
        migrations.AlterField(
            model_name='message',
            name='reply_to',
            field=models.TextField(blank=True, null=True, verbose_name='reply to'),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Pending'), (1, 'Sent'), (2, 'Deferred'), (3, 'Debug')], default=0, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.TextField(blank=True, null=True, verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='message',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mailer.Message'),
        ),
    ]
