# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-13 11:21
from __future__ import unicode_literals

from django.db import migrations, models

from django.conf import settings


MAILER_SENDER_EMAILS = getattr(settings, 'MAILER_SENDER_EMAILS', ())
MAILER_SENDER_EMAILS_CHOICES = list(zip(MAILER_SENDER_EMAILS, MAILER_SENDER_EMAILS)) if MAILER_SENDER_EMAILS else None


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0005_auto_20160428_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='from_email',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='from email', choices=MAILER_SENDER_EMAILS_CHOICES),
        ),
        migrations.AddField(
            model_name='message',
            name='from_email',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='from email'),
        ),
    ]
